### PR TITLE
Make reset button (flashcard review modal) enabled for both new and due cards

### PR DESCRIPTION
**Pull request by polyipseity**
This allows putting the flashcard back temporarily while learning it.

Currently I simply add `<!--SR:!<date of today>,1,250-->` to my flashcards whenever I learn them to enable the reset button. It would be nice to have this ability builtin instead.

### CODE REVIEW

**Review by st3v3nmw — DISMISSED** [review]
Hi, thanks for the contribution 😄!

Sorry the underlying code has gone through a major refactor recently. I'm not sure if you're still available to help resolve the merge conflicts.

Stephen,

**Comment by polyipseity** [comment]
Done.

**Comment by ronzulu** [comment]
Hi @polyipseity 

Thanks for this, I updated the PR title from "Make reset button always enabled" because the button isn't "always" enabled.

It is still disabled whilst the question is shown, but always shown when the answer is.

Cheers
Ronny

**Review by ronzulu — APPROVED** [review]
All good

**Comment by st3v3nmw** [comment]
I was about to make a release and after testing the changes, it looks like a change in #873 reverted some of your changes (apologies for that). I've fixed that by reintroducing the missing changes. It looks like the reset button now behaves the same way as skipping the new card 🤔. Am I missing something?

I was thinking that it should put the new card at the back of the queue so that you can see it later.

Thoughts?

**Comment by polyipseity** [comment]
Yes, it works as expected. Thanks for the heads up.

**Pull request merged**
