### PR TITLE
Fix/bug 424 review next cache race

### LINKED ISSUE #424: [BUG] Note review doesn't open next note automatically after a review
**Describe the bug**
I the settings I activated "Open next note automatically after a review", but when I review a note, I just see the sr-date, sr-interval, and sr-ease change but the next note doesn't open automatically. I always have to click on the review button at the bottom of the window and choose which tag to review.

**To Reproduce**
1. Open a note for review.
2. Review it.
3. Notice that the next note doesn't automatically open.

**Expected behavior**
The next note should automatically open.

**Screenshots**
Not applicable.

**Versions (please complete the following information):**

-   OS: MacOS 12.3
-   Obsidian version: v0.13.33
-   Plugin version: 1.7.2
-   If on desktop, Installer version: v0.12.19

**Additional context**
Not applicable.

### PR DESCRIPTION
**Pull request by karimodm**
Fixes #424 and #582 (duplicate)

Bonus: avoids syncing for the whole vault by changing scheduledNotes within the reviewDecks in-place.

### CODE REVIEW

**Comment by ronzulu** [comment]
Hi @karimodm  I'm a little confused by the status shown by GitHub

image

Do you know why it is saying "lint_and_test Expected — Waiting for status to be reported"? My experience is that this only displays temporarily whilst the test is being performed (a minute or two)

Cheers
Ronny

**Comment by karimodm** [comment]
I think the workflow is waiting for an approval to be run! Can you please approve @ronzulu or we have to ask @st3v3nmw ?

**Comment by ronzulu** [comment]
> I think the workflow is waiting for an approval to be run! Can you please approve @ronzulu or we have to ask @st3v3nmw ?

Hi @st3v3nmw

@karimodm's fix LGTM and has also been tested by [@axb](https://github.com/axb21). Could you please approve and merge. I don't think this is something I can do.

Cheers
Ronny

**Review by st3v3nmw — APPROVED** [review]
Hi @karimodm,

Thanks for the fix!

**Comment by ronzulu** [comment]
Hi @st3v3nmw

I'm pretty sure that by fixing this @karimodm also fixed:
#437 [BUG] Update number of notes after a review
#837 [BUG] the number of notes to be reviewed in status bar is incorrect

Could you please check. Would be great if we can close off another 2 issues!

Cheers
Ronny

**Pull request merged**
