### PR TITLE
Fix extra note review panes being added

### PR DESCRIPTION
**Pull request by AB1908**
Report by @kometenstaub on Discord: https://discord.com/channels/686053708261228577/707816848615407697/1051105667383033906

### CODE REVIEW

**Comment by AB1908** [comment]
Err, should I format the readme?

**Comment by st3v3nmw** [comment]
> Err, should I format the readme?

`npm run format` should fix it

**Comment by AB1908** [comment]
22 files changed ☠️

**Comment by st3v3nmw** [comment]
> 22 files changed skull_and_crossbones

Hmm, that's weird 😄 

Lemme just merge it and fix from my end, I only get 1 file change with prettier

**Review by st3v3nmw — APPROVED** [review]
LGTM

**Pull request merged**
