### PR TITLE
[FIX] Bug #841.

### LINKED ISSUE #841: [BUG] Incorrect display of the card content when the title embedded-link is inserted in not English note.
**Describe the bug**
If I use an embedded header link as the body of a multiline card (`?`), then this body is displayed incorrectly when review. The content is shown according to a completely different heading of the note.

Moreover, this happened only with a card from a note not in English (in Russian). A similar card from a similar note, but completely in English, works fine.

These are the files for reproduce and behavior comparison:
[`Когнитивные искажения.md` - Russian note (bug is reproducing)](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13928771/default.md)
[`Cognitive distortions.md` – English note (works well)](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13928772/Cognitive.distortions.md)

**To Reproduce**
1. Download the note, which reproduce bug [`Когнитивные искажения.md` - Russian note (bug is reproducing)](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13928771/default.md).
2. Add note to your development Obsidian vault.
3. Go to "Review flashcards" modal.
4. Find card from note with "Как можно классифицировать когнитивные искажения?" ("How can cognitive distortions be classified?") question.
5. Click "Show answer".
6. The answer will not contain the information that was expected.

**Expected behavior**
The information is expected to match with the answer indicated in the description of the card. As it happens in the English version of a similar note: [`Cognitive distortions.md` – English note (works well)](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13928772/Cognitive.distortions.md).

**Screenshots**

**Bad behavior from Russian note with bug reproduce:**

image
image

**Good behavior from English note:**

image
image

**Versions (please complete the following information):**
-   OS: Windows 11 (21H2)
-   Obsidian version: v1.5.3
-   Plugin version: v1.11.0
-   If on desktop, Installer version: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.16 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36`

### PR DESCRIPTION
**Pull request by Steindvart**
## What does this PR?

1. Fixed #841.
2. Actually, now the embedded header link as card answer will work correctly for all non-ascii characters.

## Old behavior

Prior to these changes, the regular expression was triggered on unicode characters and which led to their removal from the comparing strings. That led to incorrect behavior.

It used to look like this: ```/[\W\s]/g```. 

For example:
Bug_0

## Solution

Changed regex for cleaning header string of unwanted characters. Now, it remove only non-letter symbols (`!*/@%^` etc...) without affecting  letter symbols of Unicode and digits. And we get the correct choice and render of the header, no matter what characters are used.

Now, it's look like: ```/[!-\/:-@\[-`{-~}\s]/g```.

Now it works great with anything characters.

For example:

1. Unicode
Bug_1
Bug_3

2. Not Unicode
Bug_5
Bug_6

## Backward Compatibility
Is safe. There don't seem to be any changes that could potentially lead to problems here :)

### CODE REVIEW

**Comment by Steindvart** [comment]
@st3v3nmw should I put changes to [Changelog.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/blob/master/docs/changelog.md) when PR will be applied?

And how i can run lint and tests on GitHub? I ran this on my machine and tests is all passed. Lint let a lot of warnings in all files of source code, in which i don't made changes.

Bug_4

**Comment by ronzulu** [comment]
Hi @Steindvart 

I've had similar problems at times.

If `pnpm lint` reports errors (regardless if I changed the reported files or not) I run `pnpm format`.

Then I run `pnpm lint` again.

Git shows that many local files were changed. However, when I commit those changes and then do a `preview pull request ` only the files that I changed gets listed.

That is the sequence (from memory). Would be good to get to the bottom of this.

Of course, YMMV

Cheers
Ronny

**Comment by st3v3nmw** [comment]
@Steindvart,

For the first contribution, GitHub has a policy that a maintainer has to trigger the tests to run on GitHub. Once we get either of your PRs in, the tests will run automatically after every push

**Comment by Steindvart** [comment]
> Hi @Steindvart,
> 
> Thanks for the contribution, please look into the linting issues with the `NON_LETTER_SYMBOLS_REGEX` regex. There are two unnecessary escapes: `\/` and `\[`

Done 👌🏻.

**Review by st3v3nmw — APPROVED** [review]
Approved!

**Comment by ronzulu** [comment]
Good to know!

> For the first contribution, GitHub has a policy that a maintainer has to trigger the tests to run on GitHub. Once we get either of your PRs in, the tests will run automatically after every push

**Pull request merged**
