### PR TITLE
[FIX] isEqualOrSubPath function

### PR DESCRIPTION
**Pull request by 4Source**
Added better description discussed in #972
Stopp using the normalize function discussed in #1033

### CODE REVIEW

**Review by ronzulu — CHANGES_REQUESTED** [review]
Hi @4Source LGTM, could you update the change log. Thanks!

**Comment by 4Source** [comment]
@ronzulu what I am doing wrong? I run ``npm run changelog``

**Comment by ronzulu** [comment]
Hi @4Source.

There are actually a few different issues here:

1. How updates to the change log should be done for a PR
2. Incorrect updating of references within [Major reworking of the documentation #1032](https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/1032)(my fault)
3. Auto generation of the change log

# Updating the change log in a PR

I don't think we can use auto generation of the change log whilst working on a PR as it generates the change log based on what has already been merged into master (I believe).

So I've always just manually updated the change log as described in "Add your change to the [Unreleased] section of the changelog" in https://www.stephenmwangi.com/obsidian-spaced-repetition/contributing/#code.

So I think that's probably what needs to happen now with your PR.

# Incorrect updating of references (my fault)

Background

With the major reworking of the documentation https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/1032, I created a test vault for taking screenshots for the user documentation.

I tried to create this under the existing directory structure, i.e. under `/docs`. But I can find a way to stop `mkdocs` from including those files within the generated static website.

So my solution was to create a new level in the directory structure, as:
image

I tried to change all references, but I didn't catch all, including the reference in file (root level) `/changelog.md`.

I have fixed this now on the documentation branch.

# Auto generation of the change log

Out of curiosity I ran `pnpm run changelog` to update the change log automatically (something I've never needed to do).

For some reason even though `docs/docs/changelog.md` is specified in the command `auto-changelog --template=compact --package && npx prettier --write docs/docs/changelog.md` (`package.json`), the change log was generated at `/changelog.md`.

This seems to also be the case in what happened with you… `/changelog.md` got updated rather than `docs/changelog.md`.

**Comment by 4Source** [comment]
> # Auto generation of the change log
> Out of curiosity I ran `pnpm run changelog` to update the change log automatically (something I've never needed to do).
> 
> For some reason even though `docs/docs/changelog.md` is specified in the command `auto-changelog --template=compact --package && npx prettier --write docs/docs/changelog.md` (`package.json`), the change log was generated at `/changelog.md`.
> 
> This seems to also be the case in what happened with you… `/changelog.md` got updated rather than `docs/changelog.md`.

I think this should be possible to auto generate the unreleased section with actions

**Review by ronzulu — APPROVED** [review]
Thanks

**Comment by st3v3nmw** [comment]
> This seems to also be the case in what happened with you… `/changelog.md` got updated rather than `docs/changelog.md`.

`changelog.md` is a symbolic link to `docs/changelog.md`. It mostly works okay but gets all messed up on a non-unix OS.

---

Because of the conflicts we've been having with the `changelog.md` file, we can stop updating the file within the PRs and only do it during releases. I'll update the docs..

**Pull request merged**
