### PR TITLE
Support for atomic clozures

### PR DESCRIPTION
**Pull request by Stefanuk12**
# Addresses

#730, #450

### CODE REVIEW

**Comment by Stefanuk12** [comment]
Some test cases do fail, not sure why...

**Comment by Stefanuk12** [comment]
I've implemented my idea. Not able to get the translations of course but I also modified the tests and such. By default, the original behaviour is seen.

**Comment by Stefanuk12** [comment]
This could be expanded on and allowing control of this behaviour per flashcard instead of a global setting. I'm not sure the best way of doing this so I did not include it.

**Comment by Stefanuk12** [comment]
There's currently a bug where the scheduling data is not included within the card text. I need to add a look ahead for that.

**Comment by PaperOrb** [comment]
Can't wait for this to be merged because adding a newline before and after every piece of text that I want converted into a card is ugly and tiresome.

**Comment by PaperOrb** [comment]
Does the force-push mean that this was added to the main repository?

**Comment by Stefanuk12** [comment]
> @Stefanuk12  Does the force-push mean that this was added to the main repository?

Nope, I'll close this PR - I forgot to. The new update broke a lot of things so I'll need to work on alternative: implementing anki-type cards

**Pull request closed without merging**
