### PR TITLE
Add custom cloze tokens

### LINKED ISSUE #387: [FEAT] Adding support for strikethrough/custom cloze
**Is your feature request related to a problem? Please describe.**
Currently highlights are utilized which turn out to ne impotant as visual cues for me while reading. If we could have custom clozes, we could have out own symbols to work with!!

**Describe the solution you'd like*
We could have any set of symbols for this plug-in to search for. We can just enclose the cloze in those symbols which we want to assign.
eg `__cloze__`or `~~ cloze~~`or `₹₹cloze₹₹`Anything really.

### LINKED ISSUE #556: [FEAT] Custom cloze tokens
Currently the plugin provides `==highlights==`, `**bold text**`, and `{{curly brackets}}` (d8c0e9eca2c569f38dd2d656b564d4656c0ec1d3) for clozes. It might be better to allow user-inputted characters as the opening and closing tokens like the separator options now.

However, currently you can enable all three cloze options simultaneously, unlike the separator options where you can only specify one separator, so this might need to be handled by either:
1. Multiple cloze tokens can be specified (perhaps extend this to the separator options)
2. Add the custom token option while keeping the current three options (maybe deprecate the latter later)

I am willing to put the work into implementing it but I want to see if this is a good idea first.

### PR DESCRIPTION
**Pull request by polyipseity**
I have decided to implement custom cloze tokens (closes #556) myself.

For now, I have simply added two text field settings defaulted to empty. Empty means not using any custom cloze tokens. The existing three cloze settings are kept.

Edit: also closes #387

### CODE REVIEW

**Comment by polyipseity** [comment]
I did some digging around and found that this should also fix #387.

**Comment by Newdea** [comment]
it seems pretty good, @st3v3nmw  hope the master branch will merge it soon.

**Review by st3v3nmw — CHANGES_REQUESTED** [review]
Hi, thanks for the contribution 😄!

Sorry the underlying code has gone through a major refactor recently. I'm not sure if you're still available to help resolve the merge conflicts.

Stephen,

**Comment by polyipseity** [comment]
Done, not too hard.

**Comment by st3v3nmw** [comment]
Hi,

We ended up going with https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/943 instead.

I've just made a release (v1.13.0) that ships with custom cloze patterns 🥳 all thanks to https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/943. The updated documentation is live [here](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/cloze-cards/#cloze-types).

I'll go ahead and close this PR now.

Cheers.

**Pull request closed without merging**
