### PR TITLE
Support for many clozures within a single flashcard

### PR DESCRIPTION
**Pull request by Stefanuk12**
# Overview

Currently, a flashcard can only have one cloze and the rest are treated as highlights. This PR hides and treats all possible clozures. The new system is also simpler and allows more characters to be easily added or removed in the future.

Note: I accidentally created a new branch from my previous PR which results in the weird commit history. View the files changed for a better overview...

# Changed behaviour

## Before

*creates two flashcards*

```
many text
such surprise [...] more ==text==
some text after
```

```
many text
such surprise ==wow== more [...]
some text after
```

## After

```
many text
such surprise [...] more [...]
some text after
```

# Addresses

#486

### CODE REVIEW

**Comment by Stefanuk12** [comment]
This should fix #486

**Review by st3v3nmw — CHANGES_REQUESTED** [review]
Hi, thanks for the contribution 😄!

Sorry the underlying code has gone through a major refactor recently. I'm not sure if you're still available to help resolve the merge conflicts.

Stephen,

**Comment by Stefanuk12** [comment]
Yeah, I'm currently working on implementing an Anki card parser which could be an alternative to this PR. However, a global switch (like implemented within this PR) isn't ideal, so I might not merge unless someone can think of a more intuitive solution.

**Comment by Stefanuk12** [comment]
Going to work on re-creating this.

**Pull request closed without merging**
