### PR TITLE
add translation: zh-cn

### PR DESCRIPTION
**Pull request by artefaritaKuniklo**

### CODE REVIEW

**Comment by Newdea** [comment]
文档都翻译了，很赞

**Comment by Newdea** [comment]
文档都翻译了，很赞

**Review by ronzulu — APPROVED** [review]
Thanks for the contribution

**Comment by ronzulu** [comment]
Hello @artefaritaKuniklo I've been making significant changes (hopefully improvements!)  to the user documentation, see https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/1029.

You may wish to update the Chinese translation when this is ready.

Cheers
Ronny

**Pull request merged**
