### PR TITLE
Add card editing modal and edit later tagging

### PR DESCRIPTION
**Pull request by AB1908**
To follow up on the general ideas of #414, #433, #269, #376, I went ahead and added two new features:
- An edit later tag which has a default value of `#edit-later`. Can be toggled on as a setting.
- A card editing modal, inspired by chhoumann/quickadd's `wideInputPrompt` class.

Both implementations are rather hacky IMO but I'm open to suggestions to clean it up.

### CODE REVIEW

**Comment by AB1908** [comment]
I'd also like to split the "edit later" impl and the "edit in modal" implementation into two diff version based on commit for cleaner history purposes but not sure how to do that. Do I add tags to commits?

**Comment by FelixGibson** [comment]
@AB1908 happy to do that. I have added some interesting and might useful features in my fork. I'll  try to pull request to the upstream these days.

**Comment by AB1908** [comment]
Sounds great! I go by the same handle on Obsidian's Discord in case you want to chat.

**Comment by st3v3nmw** [comment]
Hey @AB1908, please resolve the merge conflicts so that we push this. I'd love these changes to go in. Thanks!

**Comment by AB1908** [comment]
Will do! There were a few questions:

- do you want to keep the open edit later in background option? I switched it to adding a tag.
- my flashcard counts are wrong and I couldn't figure out how to update the deckTree correctly. I think I needed to delete the flashcard.

**Comment by st3v3nmw** [comment]
Thanks.

> do you want to keep the open edit later in background option? I switched it to adding a tag.

A tag is better, I think.

> * my flashcard counts are wrong and I couldn't figure out how to update the deckTree correctly. I think I needed to delete the flashcard.

Lemme look into that bit of the code & see if I can figure out what's up

**Comment by AB1908** [comment]
I finally finished that today. I'll still need to pull down the changes and test locally.

**Comment by st3v3nmw** [comment]
Merged via https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/587, thanks!
Will be trying this out over the next few days.

**Comment by AB1908** [comment]
Err, I'm guessing it probably won't work and you should probably revert this haha. I'm redesigning my fork to support crud from the ground up.

**Comment by st3v3nmw** [comment]
Oops, just saw this.
I tested it a little and it works fine, built a little on top of it too on https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/589. Hopefully it won't be too difficult to redesign on top of the current master branch.
Anyways, it's all good! 👍🏾

**Pull request merged**
