### PR TITLE
Make the note review pane optional

### LINKED ISSUE #458: [FEAT] Remove the automatic loading of notes review queue pane
**Is your feature request related to a problem? Please describe.**
I don't use it so I don't want it cluttering my sidebar. Unfortunately, it keeps reopening after restart.

### PR DESCRIPTION
**Pull request by AB1908**
- Note review pane is enabled by default
 - Perhaps the note review logic could be optimized by checking this setting
- Fixes #458

### CODE REVIEW

**Comment by AB1908** [comment]
It's a bit presumptuous of me to add a new dep for managing versions automatically. I'll probably revert that commit on request.

**Comment by AB1908** [comment]
Reverted that anyway lol. Let me know if any other changes are necessary.

**Comment by AB1908** [comment]
Hi @st3v3nmw, I accidentally modified the versions in the manifest. Do you want to cut a new release or would you like me to revert the manifest version back to the original value so you can release in your preferred manner instead?

**Comment by st3v3nmw** [comment]
Hi @AB1908, I'll be making a release this weekend after some tests, it's fine, we don't have to change it

**Comment by AB1908** [comment]
Good to know, thanks!

**Pull request merged**
