### PR TITLE
feat: Option for viewing sr decks and cards in tabs

### PR DESCRIPTION
**Pull request by KyleKlus**
This pr implements the ability to open the views (deck view and card view) of the sr plugin in a tab/window, rather than in a modal. This ability is turned off by default and can be turned on via a toggle in the ui settings of the sr plugin.
Further more one can also limit the size of the ui within a tab via the already existing flashcard size setting.

This should also satisfy the issues #819, #950 and #1180 partly, but I can also add the open file in new tab button, if that is alright with you, as I've already implemented that on an unpublished branch.

image
_The deck list in a tab_

image
_A card in a tab_

image
_New setting in the "User Interface" tab_

### CODE REVIEW

**Comment by KyleKlus** [comment]
Hi, sadly I cant get the import sorting to work, as the formatter doesnt fix any sorting issues for me.

**Comment by KyleKlus** [comment]
I've also discovered that not just my new ui breaks in horizontal mode on mobile, but all the other ui too, so I think, that fixing that should be a different pr, as this one is already getting quite big.

I can take care of fixing that later on in a different pr.

**Comment by BlitzVI** [comment]
hey ik this might be a dumb questions because i do not know how to use github but i'd really like to use this feature but i dont see the toggle in user interface even tho the merge was committed 5 days so can you please help me out? tysm in advance!

**Comment by KyleKlus** [comment]
Hi, the new feature will only be visible in obsidian once a new release version has been published. 

So you could either wait till then or you would have to build a version of the plugin for yourself, as described in the contributing section on the website for this plugin.

**Comment by BlitzVI** [comment]
ah how can i build a version of this plugin using this fork for myself? i'd really like to try this out rn as i think it would be really helpful for my workflow

**Pull request merged**
