### PR TITLE
fix sidebar note display

### PR DESCRIPTION
**Pull request by Newdea**
FYI, it's a bug posted here https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/issues/76 , which can't show note properly on sidebar, because of Div("nav-file").style.display = "none".

### CODE REVIEW

**Comment by st3v3nmw** [comment]
Hi @Newdea, I've tried google translating https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/issues/76 but I still don't understand what the issue is. Could you please provide some more details?

**Comment by Newdea** [comment]
for example, my vault has 4 files with `#clean-up` tag (new add), and sr plugin setting of `tag to review` has the same tag, but the sidebar reveiw queue view dont show the 4 files under new, even restart obsidian.

here is the settings:
Screenshot_2024-09-24-14-04-18-236_md obsidian-edit

tag file
IMG_20240924_134733

review queue
IMG_20240924_134616

If you have questions, feel free to ask

BR

**Review by st3v3nmw — APPROVED** [review]
Okay, I see what the issue is. Please check the merge conflict, I can't fix it through the UI.

Thanks.

**Comment by Newdea** [comment]
Hey @st3v3nmw   I messed this up. Close this PR and reopen it in PR #1093.

**Pull request closed without merging**
