### PR TITLE
Support RTL flashcards specified by frontmatter "direction" attribute

### PR DESCRIPTION
**Pull request by ronzulu**
This addresses issue [RTL Support](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/335)

User documentation also updated to describe.

### CODE REVIEW

**Comment by ronzulu** [comment]
The "lint_and_test" step fails even though this PR did not change any configuration files.

See [ [DEV] Code submission "lint_and_test" fails with error ERR_PNPM_OTHER_PM_EXPECTED #936 ](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/936)

**Comment by st3v3nmw** [comment]
> The "lint_and_test" step fails even though this PR did not change any configuration files.

Fixed in #939

**Comment by ronzulu** [comment]
Hi @st3v3nmw , hope you are doing okay.

If you could please review this so that we can merge it into master.

Thanks
Ronny

**Review by st3v3nmw — APPROVED** [review]
LGTM!

**Pull request merged**
